version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8080:8080" # как в EXPOSE сервера

  client:
    build: ./client
    ports:
      - "3000:3000" # как в CMD клиента
    depends_on:
      - server
